### ISSUE TITLE
Can he write text?

### ISSUE THREAD

**Issue by panikajo** [GeorgiyDemo/InstagramToTelegram#5]
Can he write text?

**Comment by GeorgiyDemo** [comment]
Смотря что ты имеешь ввиду))
Бот только умеет перекидывать фото/видео с инсты по тегу в телегу и все

**Comment by panikajo** [comment]
О))). Ну мне надо чтобы он текст тоже умел скидывать в группу.
Фото+текст

**Comment by GeorgiyDemo** [comment]
Ну, он во вложениях к фото может кидать текст
Отдельно текст не может т.к. это противоречит логике инсты ¯\_(ツ)_/¯
![photo_2020-06-14 01 10 40](https://user-images.githubusercontent.com/16972045/84580021-e171dc00-addb-11ea-8a1b-8863e207fc3d.jpeg)
